### ISSUE TITLE
Package asking for Google Mobile Ads SDK app ID

### ISSUE THREAD

**Issue by DonnaxNL** [FlutterFlow/flutterflow-ui#30]
**Issue:**
This package depends on [Google Mobile Ads](https://pub.dev/packages/google_mobile_ads), which I don't use in my app, but it still asked for an application ID.

E/AndroidRuntime(20378): FATAL EXCEPTION: main
E/AndroidRuntime(20378): Process: app.blueplates.mobile, PID: 20378
E/AndroidRuntime(20378): java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
E/AndroidRuntime(20378): 
E/AndroidRuntime(20378): ******************************************************************************
E/AndroidRuntime(20378): * Invalid application ID. Follow instructions here:                          *
E/AndroidRuntime(20378): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
E/AndroidRuntime(20378): * to find your app ID.                                                       *
E/AndroidRuntime(20378): * Google Ad Manager publishers should follow instructions here:              *
E/AndroidRuntime(20378): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
E/AndroidRuntime(20378): ******************************************************************************
E/AndroidRuntime(20378): 
E/AndroidRuntime(20378): 
E/AndroidRuntime(20378): 	at android.app.ActivityThread.installProvider(ActivityThread.java:8215)
E/AndroidRuntime(20378): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7746)
E/AndroidRuntime(20378): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7566)
E/AndroidRuntime(20378): 	at android.app.ActivityThread.access$1500(ActivityThread.java:301)
E/AndroidRuntime(20378): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
E/AndroidRuntime(20378): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(20378): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(20378): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/AndroidRuntime(20378): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20378): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(20378): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Workaround:**
Using the sample app id from the [Quick Start](https://developers.google.com/admob/android/quick-start) guide.

**Comment by RolandoQuintana** [comment]
I'm having this same problem. Any solutions?
